###
GET http://localhost:3000/api/persons HTTP/1.1

###
GET http://localhost:3000/api/getAdmin HTTP/1.1

###
GET http://localhost:3000/api/getUsers HTTP/1.1

###
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "emailPerson": "Test_3@gmail.com",
    "passwordPerson": "Manuelg2pcfay0leq5q092Castellanos"
}

###
POST http://localhost:3000/api/signUp HTTP/1.1
Content-Type: application/json

{
    "name1Person": "Adriana",
    "lastname1Person": "Prueba",
    "documentPerson": 8882332392,
    "emailPerson": "manuel101284@outlook.com",
    "profilePerson": 3,
    "institutionPerson": "Colegio 1",
    "agePerson": 16
}

###
POST http://localhost:3000/api/newAdmin HTTP/1.1
Content-Type: application/json

{
    "name1Person": "Manuel",
    "lastname1Person": "Castellanos",
    "documentPerson": 12345678,
    "emailPerson": "Test_3@gmail.com",
    "agePerson": 16
}

###
POST http://localhost:3000/api/newAdmin HTTP/1.1
Content-Type: application/json

{
    "name1Person": "Manuel",
    "lastname1Person": "Castellanos",
    "documentPerson": 12345678,
    "emailPerson": "Test_3@gmail.com",
    "agePerson": 16
}

###
POST http://localhost:3000/api/scoreannouncement HTTP/1.1
Content-Type: application/json

{
    "ScoreProfile": 999,
    "ScoreVocation": 123,
    "ScoreMotivation": 13,
    "ScoreLogic": 12,
    "ScoreTotal": 100

}

###
POST http://localhost:3000/api/addnewannouncement HTTP/1.1
Content-Type: application/json

{
    "documentPerson": "10004",
    "nameAnnouncement": "Convocatoria 2027",
    "descriptionAnnouncement": "Estudiante grado 11 de colegios aliados"
}



