### // THIS BRING US ALL PERSONS
GET http://localhost:3000/api/persons HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDEyMjhjNjgzMzdhMTc1N2NiNzk0OWUiLCJwcm9maWxlUGVyc29uIjoiU3R1ZGVudCIsImlhdCI6MTY3ODkxMTcwMiwiZXhwIjoxNjc4OTE4OTAyfQ.wZM2LUmAzq1BYLschArlVxUJMB0KiKMsfgPjZw7WF7E


### // THIS IS BY LOGIN FOR ALL PEOPLE
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "emailPerson": "default1@correo.com",
    "passwordPerson": "ManuelRicardo19733791"
}


### // THIS CREATE NEW STUDENT
POST http://localhost:3000/api/auth/signUp HTTP/1.1
Content-Type: application/json

{
    "name1Person": "Juan",
    "name2Person": "Salazar",
    "documentPerson": "999023",
    "emailPerson": "jsalazar@correo.com",
    "profilePerson": "Student",
    "agePerson": 16,
    "institutionPerson": "Colegio Campo de la Cruz - Atlantico",
    "statusPerson": "VERIFIED"
}


### // THIS BRING US ADMINS FROM DB
GET http://localhost:3000/api/getAdmin HTTP/1.1


### // THIS BRING US STUDENTS FROM MODEL DB
GET http://localhost:3000/api/getUsers HTTP/1.1


### // THIS BRING US THE LIST OF ANNOUNCEMENTS
GET http://localhost:3000/api/getannouncements HTTP/1.1


###  // CREATE NEW ADMINS
POST http://localhost:3000/api/newAdmin HTTP/1.1
Content-Type: application/json

{
    "name1Person": "Catalina",
    "lastname1Person": "Castro",
    "documentPerson": 988888,
    "emailPerson": "Test_27@gmail.com",
    "positionPerson": "Formador"
}


### // THIS CREATE NEW ANNOUNCEMENT
POST http://localhost:3000/api/addnewannouncement HTTP/1.1
Content-Type: application/json

{
    "documentPerson": "10006",
    "nameAnnouncement": "Convocatoria 2025",
    "descriptionAnnouncement": "Estudiante grado 11 de colegios aliados",
    "placesAnnouncement": 80,
    "dateStartAnnouncement": "04-20-2025",
    "dateFinishAnnouncement": "11-14-2025"
}

### // THIS DELETE ONE ANNOUNCEMENT
DELETE http://localhost:3000/api/deleteannouncement HTTP/1.1
Content-Type: application/json

{
    "nameAnnouncement": "Convocatoria 2026"
}

### //THIS DISABLE A ANNOUNCEMENT
PATCH  http://localhost:3000/api/disabledAnnouncement/:id HTTP/1.1
Content-Type: application/json


### // THIS REGISTER IN ONE ANNOUNCEMENT
POST http://localhost:3000/api/registertoannouncement HTTP/1.1
Content-Type: application/json

{
    "documentPerson": "999015",
    "nameAnnouncement": "",
    "birthdate": "18-03-2006",
    "gender": "Masculino",
    "document": "Cedula de Ciudadanía",
    "course": "11°",
    "sena": "NO",
    "availability": "NO",
    "phone": 3014445774,
    "phoneTwo": 3012525166,
    "sisben": "SI",
    "ethnicGroup": "NO",
    "nationality": "Colombiana",
    "disability": "NO",
    "typeDisability": "Ninguna",
    "addressStudent": "Carrera 32 # 22 - 22",
    "departmentStudent": "Tolima",
    "rural": "NO",
    "bogota": "NO",
    "stratum": "5",
    "nameGuardian": "Elizabeth Pineda",
    "relationship": "Madre",
    "documentTypeGuardian": "Cedula de Ciudadanía",
    "numberIdGuardian": "900000012",
    "emailGuardian": "epineda@hotmail.com",
    "phoneGuardian": 3007482278,
    "phoneGuardianTwo": 3024456387,
    "addressGuardian": "Carrea 32 # 22 - 22",
    "departmentGuardian": "Tolima",
    "educationLevelGuardian": "Bachillerato - completo",
    "economic": "Empleado tiempo completo",
    "family": "5 o más",
    "computer": "SI",
    "internet": "SI",
    "interests": "D",
    "activity": "C",
    "reportage": "A",
    "stake": "C",
    "webMotivation": "A",
    "why": "A",
    "methodology": "C",
    "want": "B",
    "withdrawal": "Conectividad",
    "logic1": "El orden de llegada es A, B, D, A",
    "logic2": "Seis tiburones no son completamente ciegos y tres son completamente ciegos",
    "logic3": "B",
    "logic4": "A"
}


###
PATCH http://localhost:3000/api/disabledAnnouncement/:nameAnnouncement  HTTP/1.1
Content-Type: application/json

{
    "nameAnnouncement": "Convocatoria 3000"
}


###
PATCH http://localhost:3000/api/deleteStudent/:documentPerson  HTTP/1.1
Content-Type: application/json

{
    "documentPerson": "99901"
}


### // THIS BRING US INFO ABOUT PROCESS STUDENT
GET http://localhost:3000/api/getstagestudent HTTP/1.1


### // THIS BRING US INFO ABOUT ALL ANNOUNCEMENTS
GET http://localhost:3000/api/getStatistics HTTP/1.1