###
GET http://localhost:3000/api/persons HTTP/1.1

###
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/getUsers HTTP/1.1

{
    "emailPerson": "leidy.riveraf@outlook.com",
    "passwordPerson": "lr*10006"
}

###
POST http://localhost:3000/api/register HTTP/1.1
Content-Type: application/json

{
    "name1Person": "Manuel",
    "lastname1Person": "Castellanos",
    "documentPerson": 1000002,
    "emailPerson": "correooooo@gmail.com",
    "profilePerson": 3,
    "institutionPerson": "Colegio 1",
    "agePerson": 16
}

###
POST http://localhost:3000/api/newAdmin HTTP/1.1
Content-Type: application/json

{
    "name1Person": "Manuel",
    "lastname1Person": "Castellanos",
    "documentPerson": 12345678,
    "emailPerson": "Test_3@gmail.com",
    "profilePerson": 2,
    "agePerson": 16
}

###
POST http://localhost:3000/api/scoreannouncement HTTP/1.1
Content-Type: application/json

{
    "ScoreProfile": 999,
    "ScoreVocation": 123,
    "ScoreMotivation": 13,
    "ScoreLogic": 12,
    "ScoreTotal": 100

}